### ISSUE TITLE
client.api.utils.addressToHex(acct)

### ISSUE THREAD

**Issue by ericwen** [ontio/ontology-dapi#10]
onScCallRead error: TypeError: Expected Buffer

**Comment by raisezhang** [comment]
Hi  @ericwen   

This problem has been solved in this PR (https://github.com/ontio/ontology-dapi/pull/11), developers have not yet released, you can use this package temporarily ([ontology-dapi-test](https://www.npmjs.com/package/ontology-dapi-test)), after the new version is released, you can switch back.

Thanks ~
